# Generated by Django 5.0.3 on 2024-03-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Registrations',
        ),
    ]
