# Generated by Django 5.0.3 on 2024-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderConfirm', '0002_delete_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('total', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=1000)),
                ('timestamp', models.CharField(max_length=30)),
            ],
        ),
    ]
